[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmi = { path = "../crates/wasmi" }
wabt = "0.10.0"
anyhow = "1.0.69"
wat = "1.0.61"
